# KM=METR❗
# a=float(input("Qancha kilometr: "))
# print("Bu ⟪",a,"⟫ kilometr ⟪",a*1000,"⟫ metrga teng.")
# METR=KM❗
# b=float(input("Qancha metr: "))
# print("Bu ⟪",b,"⟫ metr ⟪",b/1000,"⟫ km teng.")
# a=float(input("1 chi tomonini yozing: "))
# b=float(input("2 chi tomonini kiriting: "))
# print("4 burchak perimetri:",2*(a+b))
# print("4 burchak yuzasi:",a*b)
# a=float(input("sonni kiriting: "))
# b=float(input("nechi foyizi kerak: "))
# print("foyizi:",(a*b)/100)
a=float(input("futni kirizing: "))
print("siz kiritgan fut",0.3048*a,"metr boladi")